### ISSUE TITLE
Design Proposal of Timely Scheduler

### ISSUE THREAD

**Issue by qiuxiafei** [TimelyDataflow/timely-dataflow#208]
Hi, frank!

After pushing timely to production, my colleagues (@daoliker, @wickeychen, @bmmcq, @kai-zeng and @zpqian) and I are discussing about the event-driven stuff recently. The following is our *Design Proposal of Timely Scheduler*, even though we've discussed about it for quite a while, it's still in an early stage. Looking forward for your comments!!

# Avoiding Unnecessary Scheduling

From our production experience with Timely, we observed that the current busy-polling scheduling of operators could lead to severe CPU wastage and cause performance degradation.

As reported in issue [\#114](https://github.com/frankmcsherry/differential-dataflow/issues/114), [\#117](https://github.com/frankmcsherry/differential-dataflow/issues/117),[\#189](https://github.com/frankmcsherry/differential-dataflow/issues/189), at the moment timely workers effectively poll the operators they manage, scheduling each operator once for each call to `worker.step()`. This can tie up time in larger dataflows. Actually, we have observed performance downgrade on multiple dataflows or a large dataflow: If timely is running multiple dataflows simultaneously but only a few of them are active, the performance may be affected by useless polls on idle dataflows. The figure below shows an experiment measuring where only one out of N dataflow (x-axis) are active and we measure the throughput (y-axis) of the active dataflow.

![image](https://user-images.githubusercontent.com/261796/49427539-86baf580-f7de-11e8-804f-48590a80ec1a.png)

  A second figure below shows an experiment where a large dataflow has N conditional branches (x-axis) but only one branch of them is active actually, and we measure the throughput (y-axis) of the dataflow.

![image](https://user-images.githubusercontent.com/261796/49427561-92a6b780-f7de-11e8-99b1-73bfa5c1da76.png)

  Clearly, the above two figures show this busy-polling mechanism can cause significant waste of CPU resources.

# Event-driven scheduling

To address the issue, we propose a Timely **scheduler** design to decouple scheduling from operator execution. We collect all kinds of events (e.g., receiving of a data message) into a **reactor** (i.e., event queue with a scheduler) where the scheduler is triggered and when necessary, it creates runnable tasks to be executed.

A runnable task (we call them Ordinary Tasks) wraps Timely operator logic for processing a bunch of data and/or progress messages. Executing these tasks are carried out by the reactor as well which own the CPU resource of a worker thread. It waits for tasks to arrive on its task queue and executes them in appropriate ways.

Events are wrapped into scheduling tasks (we call them Schedule Tasks) and taken care of by the scheduler. The scheduler is free to maintain any scheduling state (e.g., buffering of inputs) if necessary and decide when a runnable task should be created. For example, the following events may trigger creation of runnable tasks:

1. On receiving input messages in queue;
2. On pending progress updates;
3. On holding capabilities (This still has the busy-polling issue, see 'Key Remarks and Open Questions' for more details).

### Guarantee

Event-driven scheduling may be more complex than polling, but any correct implementation of Timely Scheduler **MUST** guarantee that an operator will be scheduled eventually as long as it has either pending input data or unprocessed notification (or holding capability, to be discussed in more detail later).

### Configurable Scheduling Policy

As a general dataflow engine, Timely can host different dataflows. These dataflows may favor different scheduling policies. For instance, certain dataflow may want to reduce the end-to-end latency, and thus want to process the messages with the smallest timestamp first; in some other cases, we may want to stash and reorder input data, or batch several progress events into a single run for higher throughput; Certain dataflow may also want to reduce memory consume ASAP (like in the [Chain](http://ilpubs.stanford.edu:8090/580/1/2003-19.pdf) paper). In addition, in a multi-tenancy service, multiple dataflows may have different shares of CPU resource based on priority, etc. This clearly shows that no single scheduling policy can fit all.

Therefore, we should be able to plug-in scheduling policies. This will allow complex strategies to achieve priority scheduling, flow control, resource isolation, etc.

# Architecture Overview

Figure below shows the diagram of the event-driven timely scheduler's workflow, which contains general communication pattern and scheduling policy.

![image](https://user-images.githubusercontent.com/261796/49431743-22516380-f7e9-11e8-8b5c-e8cb0e59759a.png)

### Key Concepts

1. **Reactor**
  Reactor is the thread that performs the actual tasks(to execute Task's logic). Each Reactor is a single thread that is pinned to a CPU core, and there are as many Reactors as cores available. A Reactor is running like [#this](https://yuque.antfin-inc.com/oyh99m/pmmr2d/az79bl#bakglq). There are two types tasks running on Reactor: **ScheduleTask** and **OrdinaryTask** (as explained in details below).
  The implementation of task queue in Reactor what we use is the `std::sync::mpsc` queue, where multiple senders send messages to a receiver through `channel`. The `channel` has a infinite buffer and therefore senders will never be blocked. As for the receiver, we use `recv()` function which will be blocked if there is no data available. Once a message is sent to the corresponding sender, then this receiver will wake up and return that message. This blocking trait fits our design on the Reactor's task queue very well, the current thread will yield CPU if there is no task available.

1. **ScheduleTask**
  ScheduleTask is a scheduling task's wrapper object which wraps the raw messages and it will be queued into its target Reactor's *task queue* for later execution. When ScheduleTask is dequeued from task queue, it will trigger the Timely Scheduler to schedule.
1. **OrdinaryTask**
  OrdinaryTask is a wrapper of a non-scheduler execution and only produced by TimelyScheduler. Each OrdinaryTask includes an apply function which will invoke the actual logic of the operator, or install(uninstall) a dataflow or others. There are three type of messages(new stimulus) that could be wrapped into OrdinaryTask: 
    - Data Message. Data coming to some operator.
    - Progress Message. Progress messages coming to some subgraph.
    - General Control Message. Install or uninstall dataflows, cancellation of expired messages, etc.
1. **Timely Scheduler**
  Timely Scheduler is an object which contains some operators' information and a `schedule()` function. The main intention of Timely Scheduler is giving system ability to plug-in different kinds of policies, such as fair share, performance isolation, flow control and etc.
    In our design, we can re-order messages or park operators to get certain fairness when we invoke Timely Scheduler's `schedule()` method and then optionally push an OrdinaryTask into the Reactor's task queue. Furthermore, one can plug-in different scheduling policies to meet their application-specific requirements. Notably, we gain flexibility without loss of simplicity due to that Reactor's execution logic is decoupled from the timely scheduler logic.

### Execution Path

1. A message from the network arrives at the current machine, The `recv_loop()` of I/O thread obtains the `target_reactor_id` through the message header, and then uses it to create a new `ScheduleTask`, which is sent to the target Worker through `sender.send()`;
2. After receiving a `ScheduleTask`, the Reactor will call Timely Scheduler's `schedule()` function. The `schedule()` matches the message type and then invokes corresponding scheduling policy. If the message type is Data or Progress and the target operator is not scheduled and can be scheduled, a new `OrdinaryTask` is created and pushed into Reactor's task queue. If the message type is Installation, a new high-priority `OrdinaryTask` is created and pushed into Reactor's task queue.
3. After receiving an `OrdinaryTask`, the target Reactor will apply its internal function. For instance, an operator's apply function will execute the specific logic, including `compute_progress_info()`, `operator.PEP()`, `operator.PIP()`, and finally `update_local_progress_tracker()`;
4. When the `operator.PIP()` function is called and there is newly generated data which needs to be sent to its downstream operator, if the downstream is intra-thread or intra-process,  then a new `ScheduleTask` will be created in the `Pusher.push()` function, and passed to target Reactor by `sender.send()`; and if the downstream operator is on another machine, the associated `Pusher.push()` function will pass the message to the `send_loop()` function of the I/O thread.

# Key Discussions and Questions

### Atomicity of Progress Batch

As described [in this blog post](https://github.com/frankmcsherry/blog/blob/master/posts/2015-12-19.md#a-distributed-protocol-for-tracking-progress), the key point to correct progress tracking in a distributed setting is sending all increments and decrements of an operator in an atomic batch.

- For a non-subgraph operator, after scheduling it once, all changes in progress are drained into a `local_poinstamp` buffer. The buffer is transferred and processed as an atomic batch (since all items in it are sent and received by `Progcaster` as a single message), so it's trivial for these operators to achieve atomicity.
- For subgraph operators, a little bit more care should be taken, because they perform progress tracking independently while they act like an ordinary operator in parent scope at the same time. No matter what progress operators in child scope have made, from the parent scope's view, before the child scope's subgraph being scheduled, the child did nothing. When the child scope's subgraph is executed, it should perform all the following in one shot to achieve atomicity:
  - Move scope's input messages count to operators attached to child zero and report as consumed.
  - Report child zero's input message count as produced.
  - Report child zero's frontier as internal capability.

### Nested Scope

We treat subgraph as a special operator which only update and propagate progress messages and notifications. This  guarantees to be correct, because:

1. **Data Transferring**. Data channels connect outer and inner operators directly, timestamps are changed by pushers when entering and leaving a scope. Since this structure will remain unchanged, it still works.
2. **Progress Tracking**. Progress work done in some subgraph may have effect on its parent scope and child scope. So after progress work of a subgraph its self is done, it should:
   - Rewrite consumed / produced / frontier on child zero to its 'operator agent' in parent scope, and importantly, ask Timely Scheduler to schedule parent subgraph.
   - If a child is also a subgraph, ask Timely Scheduler to schedule it, too.

### Scheduling Operators Holding Capability

 Issue [#117](https://github.com/frankmcsherry/timely-dataflow/issues/117) discussed five signals indicating "needs to demand rescheduling":

> 1. An operator may have input messages in queue.
> 2. An operator may hold capabilities.
> 3. An operator may have progress updates in queue.
> 4. An operator may have recently performed work.
> 5. An operator may have requested to be scheduled.

However, we found that condition #2 above may cause busy-waiting problems, even if we solve the busy-polling issue by adopting an event-driven approach. As an example, consider two different ways of using capabilities: (1) the `input` operator wants to set capabilities so that downstream operators are warned that data might come out of it; (2) an operator may temporarily hold some data internally to wait for certain frontier or notification, as in the [word-count](https://github.com/frankmcsherry/timely-dataflow/blob/master/examples/wordcount.rs) example. For case (2), rescheduling the `unary_frontier` operator may cause waste of CPU resource, as the operator can do nothing without new incoming progress.

This indicates that capability is not a good sign to tell whether if there is more to do for an operator. We need to peel this indicator functionality off capability (and this is the reason I consider this as an abuse of capabilities).

### Preventing Faulty/Malicious User Codes

User-defined operator logic may block the reactor indefinitely. To solve this issue, we can separate scheduler-related tasks, including `SchedulerTask`, and `OrdinaryTask` (such as control-related tasks), from operator tasks. Each of them is put on a separate reactor. As the workload of scheduler-related tasks is usually light, we can have both reactors share the same CPU. But splitting tasks into individual reactors, also threads, may introduce extra message passing and state synchronization, we're not sure if this is a good choice.

### Async Calls

A user-defined operator may produce an unbounded number of records, while to make the Timely system robust (in the future), all the buffers in the system need to be bounded. This mismatch will inevitably cause blocking when pushing out messages, and in turn, block the entire worker thread (even with event-driven mechanism). Therefore, we argue that the operator interface needs to be asynchronous, return a future (or something similar like async Task in C#).

# Appendix
### Pseudocode

1. Common Data Structure

   ```rust
   struct DataMsg {
       data: ::comm::Message,
       target_df_id: u32,
       target_op_id: u32,
       target_puller_id: u32,
   }
   
   struct ProgMsg {
       data: ProgressMsg,
       target_df_id: u32,
       target_op_id: u32,
       target_puller_id: u32,
   }
   
   // Message wrapper
   enum MessageWrapper {
       Data(& DataMsg),
       Progress(& ProgMsg),
       Install(u32),
       Uninstall(u32),
   }
   
   // Task wrapper
   enum TaskWrapper {
       // ordinary task apply function
       OrdinaryTask(&mut FnMut),
       // schedule content
       ScheduleTask(& MessageWrapper),
   }
   ```
2. Reactor
   ```rust
   pub struct Reactor {
       // reactor index
       reactor_id : u32,
       schedule: &FnMut(&MessageWrapper),
   }
   
   impl Reactor {    
       pub fn run() {
           // try to dequeue from task queue
           while let Ok(task_wrapper) = receiver.recv() {
               match task_wrapper {
                   Task::ScheduleTask(message) => {
                       // schedule task.
                       schedule(message);
                   },
                   Task::OrdinaryTask(task) => {
                       task();
                   },
               }
           }
       }
   }
   ```
3. Timely Scheduler
   ```rust
   struct TimeScheduler {
       // access entry to all the operators
       dataflows: &[OperatorHandle],
       // sender to local reactor's task queue
       sender: Sender,
   }
   
   impl TimelyScheduler {
       pub fn schedule(&self, &msg: &MessageWrapper) {
           match msg {
               MessageWrapper::Data(data) => {
                   add_data_operator_task(data);
               },
               MessageWrapper::Progress(prog) => {
                   add_prog_operator_task(prog);
               },
               MessageWrapper::Install(index) => {
                   add_install_task(index);
               },
               MessageWrapper::Uninstall(index) => {
                   add_uninstall_task(index);
               },
               _ => {
                   panic!();
               },
           }
       }
       
       [#inline]
       fn add_data_operator_task(&self, &data: &::comm::Message) {
           push_data_into_puller(data);
           let fn_handle = get_op_fn_handle(df_id, op_id, dataflow);
           // scheduling policy
           // ... ... ...
           {...}
           // optional send
           sender.send(TaskWrapper::OrdinaryTask{fn_handle});
       }
       [#inline]
       fn add_prog_operator_task(&self, &prog: &ProgressMsg) {
           push_data_into_puller(prog);
           let fn_handle = get_op_fn_handle(df_id, op_id, dataflow);
           // scheduling policy
           {...}
           // optional send
           sender.send(TaskWrapper::OrdinaryTask{fn_handle});
       }
       [#inline]
       fn add_install_task(&self) {
           // install a dataflow
           let fn_handle = install_data_flow();
           sender.send(TaskWrapper::OrdinaryTask{fn_handle});
       }
       [#inline]
       fn add_uninstall_task(&self) {
           // uninstall a dataflow
           let fn_handle = uninstall_data_flow();
           sender.send(TaskWrapper::OrdinaryTask{fn_handle});
       }
   }
   ```
4. OrdinaryTask on Operators
   ```rust
   struct PerOperatorState<T: Timestamp> {
       ...,
       operator: Option<Box<Operate<T>>>,
       ...,
   }
   
   impl<T: Timestamp> PerOperatorState<T> {
       fn do_work(&mut self) {
           // compute current progress information
           compute_progress_info();
           operator.push_external_progress();
           operator.pull_internal_progress();
           // update subgraph's local pointstamps using
           // progress message delta on current operator
           update_local_progress_tracker();
       }
   }
   ```
5. recv_loop
   ```rust
   pub fn recv_loop(senders: Vec<std::sync::mpsc::Sender>, ...) {
       {...}
       // Consume complete messages from the front of self.buffer.
       while let Some(header) = MessageHeader::try_read(buffer.valid()) {
           {...}
           // target reactor id
           let reactor_id = header.reactor_id;
           let msg_wrapper = header.message_wrapper;
           senders[reactor].send(TaskWrapper::ScheduleTask{msg_wrapper});
       }
   }
   ```

-------------------

Edits:
1. Update picture of Architecture Overview. // 2018-12-04 17:23

**Comment by frankmcsherry** [comment]
This sounds very interesting!

As I bet you know, there is a WIP PR (#206) doing something very similar, but with a few alternate design choices (to my initial reading, more top-down than this proposal). I need to read this a bit more carefully (what I'll start doing right now), and then I'll try and do a similar thing as you've done for the design in #206 and write up a design diff, and then we can talk through the differences and which ones are easier/harder or better/worse or whatever. :D

Independently, some of the changes in #206 are probably good ideas anyhow. There is some paying down of technical debt in `subgraph.rs` which makes each of the operators independently operable, and breaks the massive method into blocks that can each be run or not run, without violating correctness. But, let me read more and I'll try and get more concrete statements back to you.

Frank

PS: And congrats on the deployment! I'd be very interested (and I bet others would to) to hear a bit about it, the good parts and the bad parts both!

**Comment by frankmcsherry** [comment]
Hi folks!

I've written down the "design" (it's rough, sorry) that is current being followed in #206. It leaves several things unspecified, in part due to my not thinking about them, and in part due to my actively having no opinion at the moment.

I'll follow up with a post comparing aspects of this design with yours, where the goal is to try and see if we mostly agree on what things should look like, and perhaps just chose different mechanisms to accomplish them.

## Timely event-driven architecture design

Timely dataflow currently schedules each dataflow it manages every time `worker.step()` is called, and each dataflow invokes each operator they manage. This is done even if these operators may have no work to do, because timely dataflow does not track much of anything about whether operators have work to do.

This polling scheduler has the effect of increasing the minimum time through `worker.step()` as the number and complexity of dataflow graphs increase, even if they have no work to do.

To correct this behavior, we should re-design the scheduling behavior of timely so that it restricts its attention to those dataflow operators that might plausibly have work to do. This write-up details one way to do this.

### Design stack

This design has a few layers in it, which build on each other but are not deeply entangled. Each should have clear guarantees provided to the other layers.

The layers that are currently spec'd out are:
    
    1. Communication: typed message transport, but no implied structure on recipients.
    2. Scheduling: Hierarchical organization of "operators", a mapping from channels to recipient operator.
    3. Dataflow: Directed edges between (ports of) operators; progress tracking for termination.

### Communication

The communication layer provides the ability to establish independent worker threads (within and across processes), and to set up typed communication channels between them.

The current design allows users to `allocate(id)` channels, where `id` is a worker-unique identifier the channel should use to identify the channel (TODO: perhaps the channel should assign these). The result are a vector of message "push" endpoints and a single message "pull" endpoint. The intent is that messages pushed into a push endpoint will eventually be pulled by the worker at the corresponding pull endpoint (if it pulls indefinitely).

To support more clear infrastructure, the communication layer also exposes methods `receive()` and `release()` which respectively poll the communication infrastructure for inbound messages and signal that the user has ceased consuming messages for the moment (and the fabric can attempt to reclaim shared resources).

To support event-driven execution, the communication fabric also provides a sequence of communication "events": statements about numbers of messages pushed into and pulled from channels by identifier. This *should* allow the user to track which channels recently and currently contain messages and perhaps should cause whoever holds their pull endpoints to be scheduled.

The intended design is that a worker wrapping some communication fabric should on "scheduling" i. invoke `receive()`, then ii. drain the shared event queue to mark various operators as schedulable, iii. execute as many of these as they see fit, and finally iv. call `release()` once it is likely that messages have been consumed (the contract on this last part is less clear at the moment).

### Scheduling

The communication fabric indicates tasks that should be scheduled because they have received messages, but there are other reasons that a task should be scheduled, and a reasonable variety of opinions on which things should be scheduled and for how long. Timely is currently cooperatively scheduled, which means that the plan is to allow anyone that should run to run, and if they blow it we have other problems (this is negotiable, but pre-emptive scheduling has some overheads, and would ideally be something you opt in to).

The scheduling machinery currently has the following design:

Each operator has an *address*, a `[usize]` that describes a sequence of scope-local identifiers indicating a path from the root to that operator. The root scheduler tracks which addresses are "unparked", in the sense that they have some reason and expectation to be scheduled soon. In each call to `worker.step()`, the root scheduler schedules any active dataflow, and each dataflow is responsible for scheduling the active operators they contain (or a subset of them, if they choose).

As operators execute, they may choose to `park()` themselves, which removes them from the set of active operators. This action is natural to perform in response to executing an operator until its inputs are drained, at which point the operator itself has no reason to be re-invoked. The operator may become unparked in the near future if it receives more inputs, but as this is all single-threaded we should be able to avoid races (the events for new messages are checked after operators park themselves). An operator may remain unparked, which is a way to indicate that it should be re-executed in the near future (perhaps it has yielded control without completing its work).

Other thread-local objects can cheaply `unpark()` arbitrary operators. For example, input operators have external reasons why they might change from inactive to active, namely when a user calls `flush` on the input, creating new output for the operator. Remote threads should also have a way to activate operators, perhaps through a thread-safe shared queue (e.g. upcalls from a Kafka reading thread). The worker can check each of these queues at the same time it checks the event queue from the communication fabric.

#### Termination

Independently, it seems operators should indicate whether they insist that a dataflow not be terminated. For example, operators that maintain capabilities, subgraphs that are tracking outstanding messages, or operators that are writing to external sources and are awaiting confirmation all want to prevent termination of their dataflow but do not require immediate scheduling.

Whereas we say an operator that request immediate scheduling is "active", we will say that an operator that needs eventual scheduling (prevents dataflow termination) is "pending". A non-pending operator does not mean the operator should be terminated; it may become pending upon the receipt of future messages (termination is a larger-scale property where we can determine that no future messages will be received).

You can have all four cross-products of "active" and "peding" bits. As examples:

* **(active, non-pending)** : Garbage-collecting operators may want to be scheduled, but only for maintenance tasks that will not themselves produce observable outputs, nor 

* **(inactive, non-pending)** : Stateless operators with no inputs, and generally operators with no inputs and no capabilities are in this state.

* **(active, pending)** : Operators with inputs and capabilities, another unsurprising combination we expect to encounter.

* **(inactive, pending)** : Operators with capabilities, but capabilities in the future of logical times, so no reason to execute at the moment.

The property of "pending" appears to be more local than "activity", as other operators or agents do not make an operator "pending", and the current design has this as private state between operators and their immediate parents (scope, dataflow, or worker).

#### Other signals

It seems reasonable that we may find other information for the operators to communicate about their scheduling needs. Natural examples include parking oneself for a certain amount of real time, or parking oneself until a specified logical time. Likewise, we may want to communicate constraints when an operator is scheduled, that it should not execute for more than some amount of real time, or produce no more than some number of output records.

The design has no opinion yet on these, other than i. we do not want to structurally rule them out, and ii. they aren't required to recreate existing timely functionality.

The hierarchical organization of scopes is one way to encapsulate specifics about scheduling information, in that it hides these details (e.g. specific logical times) from parts of the code that would be unable to reason about them. The current plan is to make room for these scheduling disciplines by e.g. paying down technical debt on subgraph.rs so that one can make new flavors with different scheduling disciplines.

### Dataflow

The schedulable dataflow and scopes have additional structure that is not detailed to the worker, but is instead maintained encapsulated in each nested dataflow scope. The dataflow structure of the channels allow scopes to reason about the flow of messages, and progress tracking allows the scopes to reason about timestamp progress and potential termination of the computations.

The dataflow layer mainly contributes "progress tracking" on top of scheduling, in which we learn about the potential future timestamped messages operators may receive on each of their inputs. When these sets become empty, the operator is able to be shut down (once it is no longer "pending").

This layer imposes structure on messages (they must bear timestamps), as well as some structure on execution (invariants are required for correct execution).

The current timely dataflow architecture has a hierarchical organization of dataflow operators into scopes, where each scope summarizes its contained behavior upwards as an operator itself. There are certain invariants about these summaries that need to be maintained for this to be correct in an otherwise asynchronous environment. They are currently enforced using the hierarchical structure of execution, where a scope has the ability to transiently break the invariants as they execute, so long as they restore them before they return control upwards. The design proposed here does not change this.

Progress information is another signal that can be supplied to operators, and we should think of it as equivalent to a data input channel. For reasons (perhaps bad reasons) we do not actually implement scope-to-operator progress information flow as a dataflow channel, and instead rely on the `subgraph.rs` types to determine the information to compute (holistically, within the scope) and present it to the operators.

This progress information is now another vector for activation of operators, and the subgraph needs to be written to determine (and minimize) the operators that may receive new progress updates. These progress changes only result from either i. external communication (channels between subgraph instances) or ii. child operator progress, and they appear compatible with an event-driven architecture in that the absence of events implies an absence of require progress actions.

**Comment by frankmcsherry** [comment]
My thinking about next steps is that

1. The #206 stuff isn't too far off from landing. Most of the layers are in place, which means connecting them, paying attention to the information they provide, and then testing inevitable breakage.
2. It would be great from my point of view to get your view on valuable diffs from the #206 design, because if the Ali design can be reduced to diffs from #206 that makes my life easier. We can move forward with #206 and easily enqueue further improvements to #206 once we get it working. In the same pile, if there are parts of the #206 design that remain unclear, we can try and further specify / prototype them to see if they would actually rather than speculatively resolve issues.
3. If you feel a fundamental revamp is mandatory to get the benefits, that complicates the next steps I'm a month into #206 at this point and tempted to conclude it in any case. That doesn't mean it prevents re-designs, just that I'd need more time to chew them over and understand them.

**Comment by wickeychen** [comment]
少侠，您的信件我已经收到了~~~~~
